### ISSUE TITLE
Instructions on how to compile/use

### ISSUE THREAD

**Issue by AM7999** [NebuPookins/ssc-to-sm#1]
Compilation instructions would be nice

**Comment by NebuPookins** [comment]
Hi, thanks for the input. I've updated the README a bit.

There's an already compiled-to-JavaScript version of the webapp at https://nebupookins.github.io/ssc-to-sm/ so if you just want to use the tool, you can go there.

If you really want to compile it (e.g. you're making code changes that you want to test), this is a standard Gradle project, so download the Gradle build tool from https://gradle.org/ and run `gradle assemble` at the root of the project.

I'll close the issue for now, but feel free to reopen if you have any further questions.
